[package]
name = "shutdownHelper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eframe = "0.22"      # oder die aktuellste Version
winapi = { version = "0.3", features = ["winuser"] }
regex = "1"
